"""add_es_fields_to_treatment_content

Revision ID: b6b256801581
Revises: c351b80fbe11
Create Date: 2026-06-07 09:56:15.678998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6b256801581'
down_revision: Union[str, Sequence[str], None] = 'c351b80fbe11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('treatment_content', sa.Column('es_intensity', sa.Float(), nullable=True))
    op.add_column('treatment_content', sa.Column('es_frequency', sa.Float(), nullable=True))
    op.add_column('treatment_content', sa.Column('es_pulse_width', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('treatment_content', 'es_pulse_width')
    op.drop_column('treatment_content', 'es_frequency')
    op.drop_column('treatment_content', 'es_intensity')
    # ### end Alembic commands ###
